config/routes.rb
Rails.application.routes.draw do

    devise_for :users
	resources :gyms do
		resources :reviews
	end
	root 'gyms#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


#get '/categories/:id' => 'gyms#category', as: "category". Not necessary anymore

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :gyms
end

app/models/gym.rb
class Gym < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :reviews

  has_attached_file :gym_img, :styles => { :gym_index => "250x350>", :gym_show => "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :gym_img, :content_type => /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :gym
	belongs_to :user
	#a review cannot exist without a user and a gym to be reviewed (if not, what are they reviewing and who?)

end

app/models/user.rb
class User < ApplicationRecord
has_many :gyms
has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
	before_action :find_gym, only: [:show, :update, :edit, :destroy]
	before_action :authenticate_user!, only:[:new, :edit]
	
	def index
		if params[:category].blank?
		@gyms = Gym.all.order("created_at DESC") #DESC is descending orden
	    else
	    @category_id = Category.find_by(name: params[:category]).id
	    @gyms = Gym.where(:category_id => @category_id).order("created_at DESC")
	    end
	end

    def category
      @gyms = Gym.where(category_id: params[:id]) 
    end

	def show
		if @gym.reviews.blank? 
		  @average_review = 0
		else
		  @average_review = @gym.reviews.average(:rating).round(2) 
		end
	end

	def new
		@gym = current_user.gyms.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@gym = current_user.gyms.build(gym_params)
		@gym.category_id = params[:category_id]

		if @gym.save
			redirect_to root_path
		else
			render 'new'
		end
	end


	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@gym.category_id = params[:category_id]

		if @gym.update(gym_params)
			redirect_to gym_path(@gym)
		else
			render 'edit'
		end

	end

	def destroy
		@gym.destroy
		redirect_to root_path
	end

	# edit and update won't have a view files, they are responsable for changes in the data base.

	private

	def gym_params
		params.require(:gym).permit(:name, :description, :address, :category_id, :gym_img)
	end

	def find_gym
		@gym = Gym.find(params[:id])
	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_gym
	before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only:[:new, :edit]

	def new
		@review = Review.new
	end
	# have view file ans create doesn't

	def create	
		@review = Review.new(review_params)
		@review.gym_id = @gym.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to gym_path(@gym)
		else
			render 'new'
		end
	end

	def edit
    end

    def destroy
        @review.destroy
        redirect_to gym_path(@gym)
    end

    def update
    	@review = Review.find(params[:id])
    	if @review.update(review_params)
    		redirect_to gym_path(@gym)
    	else
    		render 'edit'
    	end
    end

    private

    def review_params
    	params.require(:review).permit(:rating, :comment)
    end

    def find_gym
    	@gym = Gym.find(params[:gym_id])
    end

    def find_review
    	@review = Review.find(params[:id])
    end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/gyms/_form.html.erb
<%= simple_form_for @gym do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt=> "Select a gym category") %> 
  <!-- options for select requiere de un array para funcionar. Nombres están asociados al numero -->
  <%= f.input :name, label: "Gym's name" %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.button :submit %> <!-- Aca cambio los vaores default por los valores necesarios para la creacion de cada gym -->
  <%= f.file_field :gym_img %>
<% end %>

app/views/gyms/category.html.erb
<% @gyms.each do |gym|%>
<%= gym.name %>
<% end %>

app/views/gyms/edit.html.erb
<h1>Edit Gym</h1>

<%= simple_form_for @gym, html: {multipart: true} do |f| %>
  <%= f.file_field :gym_img %>
  <%= f.select :category_id, @categories %> 
  <!-- options for select requiere de un array para funcionar. Nombres están asociados al numero -->
  <%= f.input :name, label: "Gym's name" %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.button :submit %> <!-- Aca cambio los vaores default por los valores necesarios para la creacion de cada gym -->
<% end %>

app/views/gyms/index.html.erb
<h1 class="current-category"><%= params[:category]%></h1>

<% if @gyms.count == 0 %>
 <h3>There are no gyms in this category</h3>
<% else %>
 <div class="row">
	<% @gyms.each do |gym| %>
		<div class="col-md-4">
		 <a href="/gyms/ <%= gym.id %>" >
		   <%= image_tag gym.gym_img.url(:gym_index), class: "gym" %>
		 </a>
		</div>  
	<% end %>
  </div>
<% end %>

app/views/gyms/new.html.erb
<h1>New Gym</h1>

<%= render 'form' %>

app/views/gyms/show.html.erb
<div class="row">
 <div class="col-md-4">
  <%= image_tag @gym.gym_img.url(:gym_show), class: "gym-show" %>
 </div>

 <div class="col-md-8">

	 <div class="gym-info">
		<h2 class="gym-name"><%= @gym.name %></h2>
		<h3 class="gym-address"><span><em>Located in: </em></span><%= @gym.address %></h3>
		<h4 class="gym-address"><%= @gym.category.name %></h4>
		<h4 class="average-rating">Average Rating</h4>
		<div class="average-review-rating" data-score= <%= @average_review %>> </div>
		<span class="number-of-views"><em>From:</em> <%= @gym.reviews.count %> Reviews </span>
		<p class="gym-description"><%= @gym.description %></p>
	 </div>
 </div>


<div class="row">
  <div class="col-md-12">
    <div class="reviews">
	    <h1> Reviews </h1>
	      <%= render @gym.reviews %>
	      <div>
	        <%= link_to "Add Reviews", new_gym_review_path(@gym), class: "btn btn-primary" %>
	      </div>
    </div>
  </div>
</div>


</div>

<div class="links btn-group">
	<% if user_signed_in? %>  <!-- es condicional porque si se tiene nil va a salir un error -->
		<% if @gym.user_id == current_user.id %>  <!-- y si ese usuario es el creador del gym, entonces puede editar y borrar y eso -->
			<%= link_to "Edit", edit_gym_path(@gym), class: "btn btn-primary" %>
			<%= link_to "Delete", gym_path(@gym), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %> 
		<% end %>
	<% end %>
</div>



<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score');
		}
		
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MartialFind</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   <!-- Fonts -->
   <link href="https://fonts.googleapis.com/css?family=Barrio" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Oswald|Roboto" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

  </head>

  <body>

<nav class="navbar navbar-inverse">
 <div class="container-fluid">
  <div class="navbar-header">
   <%= link_to "MartialFind", root_path, class: "navbar-brand", id: "logo" %>
  </div>
  
    <ul class="nav navbar-nav">
       
      <!-- dropdown menu -->
        <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
         Gym's by style <span class='caret'></span></a>
         <ul class="dropdown-menu" role="menu">
           <% Category.all.each do |category| %>
           <li class= "<%= 'active' if params[:category] == category.name %>"> 
            <%= link_to category.name, gyms_path(category: category.name), class:"link" %>
           </li>
          <% end %>
         </ul>
       <!-- Para agregar gimnasios-->
        <% if user_signed_in? %>
         <li><%= link_to "Add Gym", new_gym_path %></li>
        <% end %>
    </ul>
  



  <!-- Aca comienza las opciones de sign up y sign out -->
  <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>  
  </ul>

 </div>
</nav>


	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

    <div class = "container">  <!-- para que no esté todo pegado a la izquierda -->
      <%= yield %>
    </div>
  
   <script src="https://code.jquery.com/jquery-2.1.0.js"></script>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@gym, @gym.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>

<% end %>



<script>
	$('#rating-form').raty({path: '/assets/', scoreName: 'review[rating]'});
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment">
   <%= review.comment %></p>

   <% if user_signed_in? %>
     <% if review.user_id == current_user.id %>
       <div class="links btn-group">
         <%= link_to "Edit", edit_gym_review_path(review.gym, review), class: "btn btn-primary" %>
         <%= link_to "Delete", gym_review_path(review.gym, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
       </div>
      <% end %>
     <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
    <h1> Edit Review </h1>
<%= simple_form_for([@gym, @review]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>

<% end %>
  </div>
</div>

<script>
	$('#rating-form').raty({path: '/assets/', scoreName: 'review[rating]'});
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">

  <div class="new-review-form">
    <h3>Know about this gym?</h3>
    <h1>Post a review</h1>
    <%= render 'form' %>
   </div>
 </div>